# Use the official Python image.
# https://hub.docker.com/_/python
FROM python:3.9

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN rm -rf __pycache__
RUN pip install --no-cache-dir -r requirements.txt
RUN ls -al

# Make port 80 available to the world outside this container
EXPOSE 8080

# Run app.py when the container launches
# "--app-dir", "src", 
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8080"]
